### ISSUE TITLE
Android N - NoSuchFieldException

### ISSUE THREAD

**Issue by falkappel** [yongjhih/streamsupport#1]
I just tested my Android App with streamsupport with the Android N Preview and got this NoSuchFieldException:

java.lang.NoSuchFieldException: No field array in class Ljava/util/ArrayList; (declaration of 'java.util.ArrayList' appears in /system/framework/core-oj.jar)
at java.lang.Class.getDeclaredField(Native Method)
at java8.util.ArrayListSpliterator.<clinit>(ArrayListSpliterator.java:209)
at java8.util.ArrayListSpliterator.spliterator(ArrayListSpliterator.java) 
at java8.util.Spliterators.listSpliterator(Spliterators.java:909) 
at java8.util.Spliterators.spliterator(Spliterators.java:889) 
at java8.util.stream.StreamSupport.stream(StreamSupport.java:232)

**Comment by yongjhih** [comment]
You can test this app that using streamsupport-1.4:

```sh
./gradlew :cheesesquare-app:installDebug
```

**Comment by stefan-zobel** [comment]
Hi Falk,

this is a known error for Android N. See https://sourceforge.net/p/streamsupport/tickets/149/
Support for Android N was only added in streamsupport release 1.4.2

You'd have to use 1.4.2 or later on Android N.

Regards,
Stefan

**Comment by stefan-zobel** [comment]
Btw, don't be perplexed that ticket #149 is assigned to the 1.4.3-stable milestone. The issue was fixed in 1.4.2, however I got the "official" confirmation from Google only after 1.4.2 was already released. So, I left the ticket open and assigned it to 1.4.3 where it is now closed.

**Comment by falkappel** [comment]
Thanks Stefan.
I think I was a little bit lost between sourceforge an github ;-)
